stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
      - src/load_data.py
      - src/get_data.py
      - data_given/data.csv
    outs:
      - data/raw/data.csv  

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
      - src/split_data.py
      - data/raw/data.csv  
    params:
    - base.random_state 
    - split_data.test_size
    outs:
    - data/processed/train_data.csv
    - data/processed/test_data.csv